"""init fakeid

Revision ID: 070c7ca8e9c6
Revises: 5ccbad759ac0
Create Date: 2023-07-14 12:49:00.726381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070c7ca8e9c6'
down_revision = '5ccbad759ac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
