"""user.role added

Revision ID: 19374ddaf26d
Revises: 920585f873b4
Create Date: 2023-07-24 21:34:55.703276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19374ddaf26d'
down_revision = '920585f873b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
