"""init fakeid

Revision ID: 5ccbad759ac0
Revises: 8798df6e4e10
Create Date: 2023-07-14 12:44:12.994811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccbad759ac0'
down_revision = '8798df6e4e10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
