"""update bd

Revision ID: 6735c01d9ab6
Revises: a8af777b5d6e
Create Date: 2023-07-23 12:52:32.881372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6735c01d9ab6'
down_revision = 'a8af777b5d6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_id', sa.Integer(), nullable=True))
    op.alter_column('posts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('posts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('posts', 'image_id')
    # ### end Alembic commands ###
