"""d

Revision ID: 718362f256a1
Revises: 2b9b1878a8d5
Create Date: 2023-07-27 14:10:54.720785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718362f256a1'
down_revision = '2b9b1878a8d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
