"""update bd

Revision ID: 920585f873b4
Revises: cb9c7d9b6dd2
Create Date: 2023-07-23 12:56:09.141366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '920585f873b4'
down_revision = 'cb9c7d9b6dd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_id')
    # ### end Alembic commands ###
