"""fds

Revision ID: 92fe6f27c0b7
Revises: 663aa3ccffa5
Create Date: 2023-07-27 14:35:27.609265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fe6f27c0b7'
down_revision = '663aa3ccffa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
