"""Something

Revision ID: a05ec04a345c
Revises: 070c7ca8e9c6
Create Date: 2023-07-15 15:22:09.757981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05ec04a345c'
down_revision = '070c7ca8e9c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
