"""fds

Revision ID: b8b7fd090c6e
Revises: d17c9c18412b
Create Date: 2023-07-27 14:23:36.732097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b7fd090c6e'
down_revision = 'd17c9c18412b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_constraint('genres_title_key', 'genres', type_='unique')
    op.add_column('posts', sa.Column('genre_id', sa.String(length=20), nullable=True))
    op.drop_constraint('posts_genre_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'genres', ['genre_id'], ['id'])
    op.drop_column('posts', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('genre', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_genre_fkey', 'posts', 'genres', ['genre'], ['title'])
    op.drop_column('posts', 'genre_id')
    op.create_unique_constraint('genres_title_key', 'genres', ['title'])
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
