"""user.role added

Revision ID: c94450d1dc72
Revises: 19374ddaf26d
Create Date: 2023-07-24 21:39:20.678917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94450d1dc72'
down_revision = '19374ddaf26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
